- id: '1576768527164'
  alias: Staande lamp aan op vast uur
  description: ''
  trigger:
  - at: '19:30:00'
    platform: time
  condition: []
  action:
  - device_id: 2263f008f5d145c59eb736ecdaac5227
    domain: switch
    entity_id: switch.son04_basic_relay
    type: turn_on
  - device_id: 2263f008f5d145c59eb736ecdaac5227
    domain: switch
    entity_id: switch.son01_basic_relay
    type: turn_on
- id: '1576768719843'
  alias: Staande lamp uit 's nachts
  description: ''
  trigger:
  - at: '23:45:00'
    platform: time
  condition: []
  action:
  - device_id: 2263f008f5d145c59eb736ecdaac5227
    domain: switch
    entity_id: switch.son04_basic_relay
    type: turn_off
- id: '1576768719844'
  alias: Staande lamp kamer uit 's nachts
  description: ''
  trigger:
  - at: '22:30:00'
    platform: time
  condition: []
  action:
  - domain: switch
    entity_id: switch.son01_basic_relay
    type: turn_off
- id: '1585594610763'
  alias: Nieuwe automatisering
  description: test
  trigger:
  - event: sunset
    offset: '1:20:00'
    platform: sun
  condition: []
  action:
  - device_id: 2263f008f5d145c59eb736ecdaac5227
    domain: switch
    entity_id: switch.son04_basic_relay
    type: turn_on
- id: '452154575135'
  alias: Staande lampen aan voor zonsondergang
  trigger:
  - event: sunset
    offset: -0:45:00
    platform: sun
  action:
  - device_id: 2263f008f5d145c59eb736ecdaac5227
    domain: switch
    entity_id: switch.son04_basic_relay
    type: turn_on
  - type: turn_on
    device_id: 907b16830ce10cd178868b59545c1b1f
    entity_id: switch.sonoff_basic_relay
    domain: switch
  mode: single
- id: '1600972481048'
  alias: eten gereed met knop
  description: ''
  trigger:
  - platform: mqtt
    topic: RFBridge/Button4
    payload: 'ON'
  condition: []
  action:
  - service: tts.google_translate_say
    entity_id: media_player.huiskamer
    data:
      message: ’Het eten is gereed!’
      language: nl
  mode: single
- id: '1600972481050'
  alias: licht boven/slinger buiten
  description: Schakelaar licht bureau boven
  trigger:
  - platform: mqtt
    topic: RFBridge/Button5
    payload: TOGGLE
  condition: []
  action:
  - type: toggle
    device_id: d1a81cde5926472b8efaebf929d9b788
    entity_id: switch.slinger_buiten_slinger_buiten
    domain: switch
  mode: single
- id: '1600972481052'
  alias: Licht vooraan uit 's nachts
  description: Lampen uit
  trigger:
  - platform: time
    at: 00:25:00
  condition: []
  action:
  - service: scene.turn_on
    entity_id: scene.buitenverlichting_vooraan_uit
  mode: single
- id: '1600972481053'
  alias: Kerstverlichting 's ochtends aan
  description: Kerstlampjes aan
  trigger:
  - platform: time
    at: 06:30:00
  condition: []
  action:
  - service: scene.turn_on
    entity_id: scene.buitenverlichting_vooraan_uit
  mode: single
- id: '1648930138993'
  alias: Staande lamp slaapkamer uit 's avonds
  description: ''
  trigger:
  - platform: time
    at: '22:30:00'
  condition: []
  action:
  - type: turn_off
    device_id: 907b16830ce10cd178868b59545c1b1f
    entity_id: switch.sonoff_basic_relay
    domain: switch
  mode: single
