
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

sensor: !include_dir_merge_list sensors/
binary_sensor: !include_dir_merge_list binary_sensors/
group: !include_dir_merge_named groups/
  
input_select:
counter:
input_boolean:
input_text:
input_number:
input_datetime:

solaredge:
  api_key: !secret solaredge-api_key
  site_id: !secret solaredge-site_id
  
vicare:
  username: !secret vicare-username
  password: !secret vicare-password
  client_id: !secret vicare-client-id
  heating_type: gas
  
#mqtt:
#  broker: localhost
#  port: 1883
#  client_id: HassIO
#  keepalive: 60
#  username: !secret mqtt-username
#  password: !secret mqtt-password
 
# Example configuration.yaml entry with single account
tado:
    username: !secret tado-username
    password: !secret tado-password
    
# Example configuration.yaml entry
#sensor:
#  - platform: solaredge_local
#    name: SolarEdge
#    ip_address: 192.168.0.162

    # Example configuration.yaml entry for Tado
device_tracker:
  - platform: tado
    username: !secret tado-username
    password: !secret tado-password
    home_id: !secret tado-home_id
  
# Example configuration.yaml entry for Google Translate TTS service
tts:
  - platform: google_translate
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
    service_name: google_say

  
# Enables the frontend
#frontend: !include frontend.yaml

# Sun entity
sun:

# enable Lovelace YAML config (ui-lovelace.yaml)
lovelace:
  mode: yaml
  # Add yaml dashboards
  dashboards:
    ha-dashboard:
      mode: yaml
      title: Dashboard
      icon: mdi:monitor-dashboard
      show_in_sidebar: true
      filename: ha-dashboard.yaml
    tablet-ui:
      mode: yaml
      title: Dashboard
      icon: mdi:monitor-dashboard
      show_in_sidebar: true
      filename: tablet-ui.yaml

# Enables configuration UI
config:


# Enables support for tracking state changes over time
history:

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# System health
system_health:

# Persons
person:

homeassistant:
  customize: !include customize.yaml


