# Basic Config
esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${upper_devicename} Fallback Hotspot"
    password: "mjxKL4JD1EW9"

captive_portal:

logger:
api:
ota:
  password: !secret ota_password



# Device Specific Config
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO10
      mode: INPUT_PULLUP
      inverted: True
    name: "${devicename}_button"
    #toggle both relays on push
    on_press:
      - switch.toggle: relay
      - switch.toggle: relay2
  - platform: gpio
    pin:
      number: GPIO00
      mode: INPUT_PULLUP
      inverted: True
    name: "${devicename}_button0"
    #toggle only relay1
    on_press:
      - switch.toggle: relay
  - platform: gpio
    pin:
      number: GPIO09
      mode: INPUT_PULLUP
      inverted: True
    name: "${devicename}_button1"
    #toggle only relay2
    on_press:
      - switch.toggle: relay2

switch:
  - platform: gpio
    name: "${devicename}_relay"
    pin: GPIO12
    id: relay
  - platform: gpio
    name: "${devicename}_relay2"
    pin: GPIO05
    id: relay2
  - platform: shutdown
    name: "${devicename}_shutdown"
  - platform: restart
    name: "${devicename}_restart"

sensor:
  - platform: wifi_signal
    name: ${devicename} Wfi Signal
    update_interval: 30s
  - platform: uptime
    name: ${devicename} Uptime
    update_interval: 120s

status_led:
  pin:
    number: GPIO13
    inverted: yes

text_sensor:
  - platform: version
    name: ${devicename} version
  - platform: wifi_info
    ip_address:
      name: ${devicename} IP Address
    ssid:
      name: ${devicename} Connected SSID
    bssid:
      name: ${devicename} Connected BSSID
    mac_address:
      name: ${devicename} Mac Wifi Address
    scan_results:
      name: ${devicename} Latest Scan Results
